server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 9000

  adminConnectors:
    - type: http
      port: 9001

host: 185.40.9.190
port: 27017
db: postcodes